// Code generated by sqlc. DO NOT EDIT.
// source: fundraise.sql

package db

import (
	"context"
)

const addFundraiseProgressAmount = `-- name: AddFundraiseProgressAmount :one
UPDATE fundraise
SET progress_amount = progress_amount + $1
WHERE id = $2
RETURNING id, product_id, target_amount, progress_amount, success, start_date, end_date
`

type AddFundraiseProgressAmountParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) AddFundraiseProgressAmount(ctx context.Context, arg AddFundraiseProgressAmountParams) (Fundraise, error) {
	row := q.db.QueryRowContext(ctx, addFundraiseProgressAmount, arg.Amount, arg.ID)
	var i Fundraise
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.TargetAmount,
		&i.ProgressAmount,
		&i.Success,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const createFundraise = `-- name: CreateFundraise :one
INSERT INTO fundraise (
	product_id,
  target_amount,
  progress_amount
) VALUES (
  $1, $2, $3
) RETURNING id, product_id, target_amount, progress_amount, success, start_date, end_date
`

type CreateFundraiseParams struct {
	ProductID      int64 `json:"product_id"`
	TargetAmount   int64 `json:"target_amount"`
	ProgressAmount int64 `json:"progress_amount"`
}

func (q *Queries) CreateFundraise(ctx context.Context, arg CreateFundraiseParams) (Fundraise, error) {
	row := q.db.QueryRowContext(ctx, createFundraise, arg.ProductID, arg.TargetAmount, arg.ProgressAmount)
	var i Fundraise
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.TargetAmount,
		&i.ProgressAmount,
		&i.Success,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const exitFundraise = `-- name: ExitFundraise :one
UPDATE fundraise
SET success = $2, end_date = now()
WHERE id = $1
RETURNING id, product_id, target_amount, progress_amount, success, start_date, end_date
`

type ExitFundraiseParams struct {
	ID      int64 `json:"id"`
	Success bool  `json:"success"`
}

func (q *Queries) ExitFundraise(ctx context.Context, arg ExitFundraiseParams) (Fundraise, error) {
	row := q.db.QueryRowContext(ctx, exitFundraise, arg.ID, arg.Success)
	var i Fundraise
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.TargetAmount,
		&i.ProgressAmount,
		&i.Success,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const getFundraise = `-- name: GetFundraise :one
SELECT id, product_id, target_amount, progress_amount, success, start_date, end_date FROM fundraise
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFundraise(ctx context.Context, id int64) (Fundraise, error) {
	row := q.db.QueryRowContext(ctx, getFundraise, id)
	var i Fundraise
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.TargetAmount,
		&i.ProgressAmount,
		&i.Success,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const updateFundraiseProgressAmount = `-- name: UpdateFundraiseProgressAmount :one
UPDATE fundraise
SET progress_amount = $2
WHERE product_id = $1
RETURNING id, product_id, target_amount, progress_amount, success, start_date, end_date
`

type UpdateFundraiseProgressAmountParams struct {
	ProductID      int64 `json:"product_id"`
	ProgressAmount int64 `json:"progress_amount"`
}

func (q *Queries) UpdateFundraiseProgressAmount(ctx context.Context, arg UpdateFundraiseProgressAmountParams) (Fundraise, error) {
	row := q.db.QueryRowContext(ctx, updateFundraiseProgressAmount, arg.ProductID, arg.ProgressAmount)
	var i Fundraise
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.TargetAmount,
		&i.ProgressAmount,
		&i.Success,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}
